id: DAEFA21A8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:45:46+00:00'
last_modified: '2022-05-26T12:44:44.041811+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    241a:
      image_group_id: I1PD95883
      title: དེ་བཞིན་གཤེགས་པ་བདུན་གྱི་སྔོན་གྱི་སྨོན་ལམ་གྱི་ཁྱད་པར་རྒྱས་པའི་མདོ་སྡེའི་མན་ངག།
      total_pages: 1044
      order: 38
      base_file: 241a.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
