id: PA563843F
initial_creation_type: ocr
source_metadata:
  volumes:
    bac3f7f588114711b84a0f262be92f0e:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: དེ་བཞིན་གཤེགས་པ་བདུན་གྱི་སྔོན་གྱི་སྨོན་ལམ་གྱི་ཁྱད་པར་རྒྱས་པའི་མདོ་སྡེའི་མན་ངག།
      total_pages: 1044
      volume_number: 38
